### ISSUE TITLE
Refactor code repetition (structs definitions)

### ISSUE THREAD

**Issue by bar9** [ebcrowder/rust_ledger#2]
Hi Eric
I am interested in this project and would like to contribute. One thing that struck me was that structs are defined multiple times, e.g. Accounts or Currencies. This will be hard to maintain. They could be moved to a types.rs or models.rs file and imported to the other files. Can I open a PR for this? Are you interested in contributions?
Cheers

**Comment by ebcrowder** [comment]
This is a great idea and will clean up the code quite a bit. Please do submit a PR!
